/**
 * Format a BrandVoiceProfile as Markdown (analytics view).
 */
export function formatMarkdown(profile) {
  const { brand, url, pagesAnalyzed, summary, tone, vocabulary, structure, personality, guidelines, aiPrompt } = profile;

  const toneTable = tone.dimensions
    .map((d) => {
      const [low, high] = d.name.split(" ↔ ");
      const bar = renderBar(d.score);
      return `| ${low.padEnd(12)} ${bar} ${high.padEnd(12)} | ${d.score}/10 |`;
    })
    .join("\n");

  return `# 🎙️ Brand Voice Profile: ${brand}

> ${summary}

**Source:** ${url}
**Pages analyzed:** ${pagesAnalyzed}

---

## Tone Spectrum

| Dimension | Score |
|-----------|-------|
${toneTable}

## Personality

**Archetypes:** ${personality.archetypes.join(", ")}
**Traits:** ${personality.traits.join(", ")}

## Vocabulary DNA

- **Total words analyzed:** ${vocabulary.totalWords.toLocaleString()}
- **Unique words:** ${vocabulary.uniqueWords.toLocaleString()}
- **Vocabulary richness:** ${vocabulary.vocabularyRichness}
- **Average word length:** ${vocabulary.averageWordLength} chars

**Power Words:** ${vocabulary.powerWords.slice(0, 15).map((w) => `\`${w.word}\``).join(", ")}
${vocabulary.jargon.length ? `\n**Industry Jargon:** ${vocabulary.jargon.join(", ")}` : ""}

## Writing Structure

- **Average sentence length:** ${structure.averageSentenceLength} words
- **Reading level:** ${structure.readingLevel.label} (Grade ${structure.readingLevel.grade})
- **Questions:** ${Math.round(structure.questionRatio * 100)}% of sentences
- **Exclamations:** ${Math.round(structure.exclamationRatio * 100)}% of sentences
- **Imperatives (CTAs):** ${Math.round(structure.imperativeRatio * 100)}% of sentences

## Brand Voice Guidelines

### ✅ Do
${guidelines.dos.map((d) => `- ${d}`).join("\n")}

### ❌ Don't
${guidelines.donts.map((d) => `- ${d}`).join("\n")}

## 🤖 AI Prompt (Copy & Paste)

Use this prompt to make any AI write in ${brand}'s voice:

\`\`\`
${aiPrompt}
\`\`\`

---

> 💡 Run without `--analytics` to get a deployable `VOICE.md` for this brand (default behavior).

*Generated by [voiceprint](https://github.com/SlashImagine/brand-voice)*
`;
}

/**
 * Format as JSON string.
 */
export function formatJSON(profile) {
  return JSON.stringify(profile, null, 2);
}

/**
 * Format a side-by-side brand comparison.
 */
export function formatComparison(a, b) {
  const diffs = [];
  for (let i = 0; i < a.tone.dimensions.length; i++) {
    const da = a.tone.dimensions[i];
    const db = b.tone.dimensions[i];
    if (db && Math.abs(da.score - db.score) >= 2.5) {
      const [low, high] = da.name.split(" ↔ ");
      const winner = da.score > db.score ? a.brand : b.brand;
      const label = da.score > db.score ? high : low;
      diffs.push(`- **${da.name}:** ${a.brand} (${da.score}) vs ${b.brand} (${db.score ?? "–"}) — ${winner} is more ${label.toLowerCase()}`);
    }
  }

  const toneRows = a.tone.dimensions.map((d, i) => {
    const db = b.tone.dimensions[i];
    const scoreA = d.score;
    const scoreB = db?.score ?? "–";
    const diff = db ? Math.abs(scoreA - scoreB) : 0;
    const flag = diff >= 3 ? " ◀ big diff" : diff >= 2 ? " ◀ diff" : "";
    return `| ${d.name} | ${scoreA}/10 | ${scoreB}/10 |${flag}`;
  }).join("\n");

  return `# Brand Voice Comparison: ${a.brand} vs ${b.brand}

## ${a.brand}
> ${a.summary}
Archetypes: ${a.personality.archetypes.join(", ")}
Traits: ${a.personality.traits.join(", ")}

## ${b.brand}
> ${b.summary}
Archetypes: ${b.personality.archetypes.join(", ")}
Traits: ${b.personality.traits.join(", ")}

---

## Tone Spectrum

| Dimension | ${a.brand} | ${b.brand} |
|-----------|${"-".repeat(a.brand.length + 2)}|${"-".repeat(b.brand.length + 2)}|
${toneRows}

---

## Key Differences
${diffs.length ? diffs.join("\n") : "Brands are relatively similar in tone across all dimensions."}

---

*Generated by [voiceprint](https://github.com/SlashImagine/brand-voice)*
`;
}

function renderBar(score) {
  const filled = Math.round(score);
  const empty = 10 - filled;
  return "◼".repeat(filled) + "◻".repeat(empty);
}
